# Generated by Django 2.2.24 on 2021-09-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('视频链接', models.TextField(blank=True, null=True)),
                ('视频名称', models.TextField(blank=True, null=True)),
                ('简介', models.TextField(blank=True, null=True)),
                ('封面照片', models.TextField(blank=True, null=True)),
                ('播放量', models.TextField(blank=True, null=True)),
                ('弹幕数', models.TextField(blank=True, null=True)),
                ('评论数', models.TextField(blank=True, null=True)),
                ('上传日期', models.TextField(blank=True, null=True)),
                ('点赞数', models.TextField(blank=True, null=True)),
                ('收藏数', models.TextField(blank=True, null=True)),
                ('香蕉数', models.TextField(blank=True, null=True)),
                ('up主名称', models.TextField(blank=True, db_column='UP主名称', null=True)),
                ('up主id', models.TextField(blank=True, db_column='UP主ID', null=True)),
                ('up主头像', models.TextField(blank=True, db_column='UP主头像', null=True)),
                ('up主介绍', models.TextField(blank=True, db_column='UP主介绍', null=True)),
                ('up主关注人数', models.TextField(blank=True, db_column='UP主关注人数', null=True)),
                ('评论1', models.TextField(blank=True, null=True)),
                ('评论2', models.TextField(blank=True, null=True)),
                ('评论3', models.TextField(blank=True, null=True)),
                ('评论4', models.TextField(blank=True, null=True)),
                ('评论5', models.TextField(blank=True, null=True)),
                ('评论6', models.TextField(blank=True, null=True)),
                ('评论7', models.TextField(blank=True, null=True)),
                ('评论8', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_list',
                'managed': True,
            },
        ),
    ]
